development:
  bin_path: /usr/local/bin
  port: 3310
  enable_star: true
  min_prefix_len: 1
  min_word_len: 1
  morphology: none
  mem_limit: 1024M
  charset_table: "0..9, A..Z->a..z,a..z, `, ~, !, @, %, ^, &, (, ), -, _, +, =, {, }, [, ], |, :, ;, ', <, >, ?, /,#" 
  #charset_table: "0..9, A..Z->a..z,a..z, U+0024->$, U+0021->!"

production:
  bin_path: /usr/local/bin
  port: 3312
  enable_star: true
  min_prefix_len: 1
  min_word_len: 1
  morphology: none
  mem_limit: 1024M
  charset_table: "0..9, A..Z->a..z,a..z, `, ~, !, @, %, ^, &, (, ), -, _, +, =, {, }, [, ], |, :, ;, ', <, >, ?, /,#" 
  #charset_table: "0..9, A..Z->a..z,a..z, U+0024->$, U+0021->!"

test:
  port: 3314
  enable_star: true
  min_prefix_len: 1
  min_word_len: 1
  morphology: none
  mem_limit: 1024M
  #bin_path: '/usr/bin'
