class RemoveDefaultvalueOfCompanyId < ActiveRecord::Migration
  def self.up
    change_column_default(:account_contacts, :company_id, nil)
    change_column_default(:accounts, :company_id, nil)
#    change_column_default(:activities, :company_id, nil)
    change_column_default(:addresses, :company_id, nil)
    change_column_default(:assets, :company_id, nil)
    change_column_default(:campaign_mails, :company_id, nil)
    change_column_default(:campaign_members, :company_id, nil)
    change_column_default(:campaigns, :company_id, nil)
    change_column_default(:comments, :company_id, nil)
    change_column_default(:company_activity_rates, :company_id, nil)
    change_column_default(:company_role_rates, :company_id, nil)
    change_column_default(:contact_additional_fields, :company_id, nil)
    change_column_default(:contacts, :company_id, nil)
    change_column_default(:document_access_controls, :company_id, nil)    
    change_column_default(:document_homes, :company_id, nil)
#    change_column_default(:document_homes_matter_facts, :company_id, nil)
#    change_column_default(:document_homes_matter_issues, :company_id, nil)
#    change_column_default(:document_homes_matter_researches, :company_id, nil)
#    change_column_default(:document_homes_matter_risks, :company_id, nil)
#    change_column_default(:document_homes_matter_tasks, :company_id, nil)
    change_column_default(:documents, :company_id, nil)
    change_column_default(:employee_activity_rates, :company_id, nil)
    change_column_default(:employee_sessions, :company_id, nil)
    change_column_default(:employees, :company_id, nil)
    change_column_default(:expense_entries, :company_id, nil)
    change_column_default(:folders, :company_id, nil)
    change_column_default(:matter_facts, :company_id, nil)
#    change_column_default(:matter_facts_matter_issues, :company_id, nil)
#    change_column_default(:matter_facts_matter_researches, :company_id, nil)    
    change_column_default(:matter_issues, :company_id, nil)    
#    change_column_default(:matter_issues_matter_researches, :company_id, nil)    
#    change_column_default(:matter_issues_matter_risks, :company_id, nil)    
    change_column_default(:matter_issues_matter_tasks, :company_id, nil)    
    change_column_default(:matter_litigations, :company_id, nil)    
    change_column_default(:matter_peoples, :company_id, nil)    
    change_column_default(:matter_researches, :company_id, nil)    
    change_column_default(:matter_researches_matter_risks, :company_id, nil)    
#    change_column_default(:matter_researches_matter_tasks, :company_id, nil)    
    change_column_default(:matter_risks, :company_id, nil)    
    change_column_default(:matter_tasks, :company_id, nil)    
    change_column_default(:matter_termconditions, :company_id, nil)
    change_column_default(:matters, :company_id, nil)
    change_column_default(:opportunities, :company_id, nil)
#    change_column_default(:roles, :company_id, nil)
#    change_column_default(:service_assignments, :company_id, nil)
    change_column_default(:service_provider_sessions, :company_id, nil)
    change_column_default(:service_provider_skills, :company_id, nil)
    change_column_default(:service_providers, :company_id, nil)
    change_column_default(:service_sessions, :company_id, nil)
    change_column :sessions, :company_id, :integer , :null => true
    change_column_default(:sessions, :company_id, nil)
    change_column_default(:time_entries, :company_id, nil)
    change_column_default(:users, :company_id, nil)
  end

  def self.down
    change_column_default(:account_contacts, :company_id, 100)
    change_column_default(:accounts, :company_id, 100)
#    change_column_default(:activities, :company_id, 100)
    change_column_default(:addresses, :company_id, 100)
    change_column_default(:assets, :company_id, 100)
    change_column_default(:campaign_mails, :company_id, 100)
    change_column_default(:campaign_members, :company_id, 100)
    change_column_default(:campaigns, :company_id, 100)
    change_column_default(:comments, :company_id, 100)
    change_column_default(:company_activity_rates, :company_id, 100)
    change_column_default(:company_role_rates, :company_id, 100)
    change_column_default(:contact_additional_fields, :company_id, 100)
    change_column_default(:contacts, :company_id, 100)
    change_column_default(:document_access_controls, :company_id, 100)    
    change_column_default(:document_homes, :company_id, 100)
#    change_column_default(:document_homes_matter_facts, :company_id, 100)
#    change_column_default(:document_homes_matter_issues, :company_id, 100)
#    change_column_default(:document_homes_matter_researches, :company_id, 100)
#    change_column_default(:document_homes_matter_risks, :company_id, 100)
#    change_column_default(:document_homes_matter_tasks, :company_id, 100)
    change_column_default(:documents, :company_id, 100)
    change_column_default(:employee_activity_rates, :company_id, 100)
    change_column_default(:employee_sessions, :company_id, 100)
    change_column_default(:employees, :company_id, 100)
    change_column_default(:expense_entries, :company_id, 100)
    change_column_default(:folders, :company_id, 100)
    change_column_default(:matter_facts, :company_id, 100)
#    change_column_default(:matter_facts_matter_issues, :company_id, 100)
#    change_column_default(:matter_facts_matter_researches, :company_id, 100)    
    change_column_default(:matter_issues, :company_id, 100)    
#    change_column_default(:matter_issues_matter_researches, :company_id, 100)    
#    change_column_default(:matter_issues_matter_risks, :company_id, 100)    
    change_column_default(:matter_issues_matter_tasks, :company_id, 100)    
    change_column_default(:matter_litigations, :company_id, 100)    
    change_column_default(:matter_peoples, :company_id, 100)    
    change_column_default(:matter_researches, :company_id, 100)    
    change_column_default(:matter_researches_matter_risks, :company_id, 100)    
#    change_column_default(:matter_researches_matter_tasks, :company_id, 100)    
    change_column_default(:matter_risks, :company_id, 100)    
    change_column_default(:matter_tasks, :company_id, 100)    
    change_column_default(:matter_termconditions, :company_id, 100)
    change_column_default(:matters, :company_id, 100)
    change_column_default(:opportunities, :company_id, 100)
#    change_column_default(:roles, :company_id, 100)
#    change_column_default(:service_assignments, :company_id, 100)
    change_column_default(:service_provider_sessions, :company_id, 100)
    change_column_default(:service_provider_skills, :company_id, 100)
    change_column_default(:service_providers, :company_id, 100)
    change_column_default(:service_sessions, :company_id, 100)
    change_column :sessions, :company_id, :integer , :null => false
    change_column_default(:sessions, :company_id, 100)
    change_column_default(:time_entries, :company_id, 100)
    change_column_default(:users, :company_id, 100)
  end
end
